//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Pol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int id { get; set; }
        public int TypeId { get; set; }
        public int Companyid { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Index { get; set; }
        public int Region { get; set; }
        public int City { get; set; }
        public int Street { get; set; }
        public int Building { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual PartnerCompany PartnerCompany { get; set; }
        public virtual PartnerType PartnerType { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Street Street1 { get; set; }
    }
}
